### ISSUE TITLE
您好，请问近期是否会发布pytorch版本？

### ISSUE THREAD

**Issue by JensenFraser** [davidlvxin/TransC#11]
作者您好：
        您的文章思路新颖，启发性很强，想作为baseline对比使用，请问近期是否会有Pytorch版本发布，或者短期有无发布计划，翻看issue时看到您18年说后续会发布pytorch版本。

祝您生活愉快，科研顺利！

**Comment by davidlvxin** [comment]
目前已经有人实现了pytorch的版本，但还没有整理出来，我争取在1个月之内把它整理放出来，但不能完全保证进度，如果比较急切不建议等待。
