### ISSUE TITLE
您好，关于subclassOf类别的Triple损失函数有一点疑问向您请教

### ISSUE THREAD

**Issue by JensenDong** [davidlvxin/TransC#14]
作者您好：  
        感谢您百忙之中抽出时间解惑。在拜读您的文章时，发现对于subclassof三种不同情况下，具体共使用了两种损失函数，但在阅读代码时发现，最终只用了较为普适的一种，请问这样选择是基于实际实验效果还是因为在前两种情况下提出的loss可以cover掉第三种情况，所以没使用论文中提出的针对第三种情况下的loss用于实际训练吗？再次感谢您！

       祝您生活愉快、科研顺利！

**Comment by JensenDong** [comment]
您好，抱歉一些细节没说清楚，上述问题中所说代码为C++版代码，非python版；同时我看到python版中也与文章所述loss有一定出入。。。

**Comment by davidlvxin** [comment]
不好意思，当时代码实现时忽略了第三种情况，因为第三种情况出现的比较少，所以影响不大。你可以自己加上那部分，在gradientSubClassof函数中加入即可，或者可以使用新版的python代码。

**Comment by JensenDong** [comment]
您好，抱歉尚有疑问。python版本的代码相比C++版本细节之处确实更加完善，但对于subclassof第三种情况似乎也没有处理，不知是否是我在看的时候遗漏掉了信息，还请您指教；另您说的没错，这种情况相对少见，如果补全这部分代码，应该是除了对 gradientSubClassof 进行改动，也需要对 calcSumSubClassOf 进行修改吧，毕竟前两种情况和第三种情况的loss计算方式本就不同。

再次感谢您百忙之中解惑，祝您生活愉快、科研顺利。

**Comment by davidlvxin** [comment]
你说的是对的，需要对两者都进行修改，抱歉时间太久了，很多细节记不太清。此外python代码是由另一位同学提供的，他可能也没考虑这种情况。但代码改起来应该并不麻烦，如果急切可以自己改一下，后续有时间我应该也会修改，但不能保证时效性。

**Comment by JensenDong** [comment]
好的好的，非常感谢您的解惑。因为与论文所述有出入，所以打算咨询过后再自行改动代码。
