### ISSUE TITLE
您好，关于代码中设置batch的问题

### ISSUE THREAD

**Issue by JensenDong** [davidlvxin/TransC#15]
作者您好：
       我看到C++以及python代码中设置了batch，但训练用的貌似应该还是随机梯度下降的方法，不太明白这里设置batch的目的是什么，请问您能否指点一二？

       祝您生活愉快、工作顺利。

**Comment by davidlvxin** [comment]
这里的设置是没有必要的，本质上代码里的batch_size为1，可以忽略这个batch的事情。

**Comment by JensenDong** [comment]
十分感谢。
