### ISSUE TITLE
yago39k数据集问题

### ISSUE THREAD

**Issue by zj-Jing** [davidlvxin/TransC#5]
您好，我关于数据集的问题有以下几点：
1. 按照论文中构建数据集的方法，应该每一个instance都归属于至少一个concept，但是在统计中发现，有大约几百个instance是没有归属于任何concept的。
2. 论文中写到yago39k的Train中有39个relation，46110个concept，但是实际数据集中只有37个relation和46109个concept。
不知道这其中是否有什么故事？第二点是否是第一点出现的原因呢？如果没有故事，那请问您是怎么处理没有concept的instance的？谢谢，期待回复！

**Comment by davidlvxin** [comment]
您好，关于您的问题有如下回复：
1. 确实有一些instance是没有concept的，这在知识图谱中是很正常的。这些instance虽然没有concept，但是还是会和其他的instance通过关系相连的，其余有concept的instance可以帮助它们学习一个表示向量，通过这些表示我们便可以预测它们应该属于哪个concept，这也可以看做是对知识图谱补全的一种方法。
2. 论文中提到的39个relation是包括了instanceOf和subClassOf两种关系，加上那37种关系就是39种了。至于concept的数量差1，可能是统计上出了一些偏差，几乎没有影响，其中并没有什么故事。

**Comment by zj-Jing** [comment]
搜嘎，谢谢您嘞！
