### ISSUE TITLE
参数cut

### ISSUE THREAD

**Issue by zj-Jing** [davidlvxin/TransC#6]
您好，请问transC.cpp中的参数cut是什么含义？

**Comment by davidlvxin** [comment]
对于一个三元组(h, r, t)，我们在训练的时候需要生成负例(h, r, t')或者(h', r, t)，这里的策略有两种，一是完全随机生成t'或h'，二是论文Training Method部分最后提到的策略，这里的cut便是随机选择第二种策略的概率。

**Comment by zj-Jing** [comment]
谢谢回答。请问现在有python版本的吗？

**Comment by davidlvxin** [comment]
最近比较忙，还没有写python版本，预计6月份可以完成。

**Comment by zj-Jing** [comment]
谢谢，期待！
