### ISSUE TITLE
您好？有没有数据集M-YAGO39呢？

### ISSUE THREAD

**Issue by 876012988** [davidlvxin/TransC#7]
![image](https://user-images.githubusercontent.com/33303996/56087126-40b22480-5e97-11e9-9e19-389177cd2ad2.png)
结果出问题了，希望大佬给予指点

**Comment by davidlvxin** [comment]
data/YAGO39K/M-valid和data/YAGO39K/M-test下面是M-YAGO39K的验证集和测试集，训练集和YAGO39K一致。
